### ISSUE TITLE
Quickstart Guide

### ISSUE THREAD

**Issue by JKSnd** [jpmikkers/DHCPServer#1]
Hi there,

I'm evaluating DHCP libraries at the moment, so I've pulled this repo and built the GUI application. I've configured it to run a server using a static IP I've assigned my NIC, then connected a few devices through a switch to this nic. I'm not seeing any action in the log window, however.

A quickstart document would be very useful. Thanks!

**Comment by jpmikkers** [comment]
Hi,

Great idea! The windows firewall silently drops all broadcast packets, which is probably why you're not seeing any traffic. Try temporarily disabling your firewall, or add an exception for DHCPServer.exe , udp port 67.

On an admin command line, this should do the trick:

`
netsh advfirewall firewall add rule name="DotNetDHCPServer" dir=in action=allow protocol=UDP localport=67
netsh advfirewall firewall add rule name="DotNetDHCPServer" dir=out action=allow protocol=UDP localport=67
`

**Comment by JKSnd** [comment]
Thanks for the tip! This worked, but required a restart (not a big deal).

So if this library were to be used as a part of another software product, would that product then require elevation every time it ran?

**Comment by jpmikkers** [comment]
no I only require it because it normally runs as a windows service. It would also work in a user mode executable (after you've added that port 67 firewall rule obviously).
