### ISSUE TITLE
.net 8 - No sign of life under Linux (Ubuntu LTS 22.04, Debian 12)

### ISSUE THREAD

**Issue by n-ice-ch** [jpmikkers/DHCPServer#20]
I have build the DHCPServer with .net 8.
This result with success for a Windows machine.
But on Linux (Ubuntu LTS 22.04) I get absolutely no sign that the code will run.

The console output is: nothing.

I saw a difference between an old implementation from DHCPServer and the current:
The OLD was:
`        protected virtual void ProcessingReceiveMessage(DHCPMessage sourceMsg, DHCPMessage targetMsg)
        {

        }
        private void AppendConfiguredOptions(DHCPMessage sourceMsg,DHCPMessage targetMsg)
        {
            
            foreach (OptionItem optionItem in m_Options)
            {
                if (optionItem.Mode == OptionMode.Force || sourceMsg.IsRequestedParameter(optionItem.Option.OptionType))
                {
                    if(targetMsg.GetOption(optionItem.Option.OptionType)==null)
                    {
                        targetMsg.Options.Add(optionItem.Option);
                    }
                }
            }

            ProcessingReceiveMessage(sourceMsg, targetMsg);
        }`

The NEW is:
`        private void AppendConfiguredOptions(DHCPMessage sourceMsg, DHCPMessage targetMsg)
        {
            foreach(OptionItem optionItem in _options)
            {
                if(optionItem.Mode == OptionMode.Force || sourceMsg.IsRequestedParameter(optionItem.Option.OptionType))
                {
                    if(targetMsg.GetOption(optionItem.Option.OptionType) == null)
                    {
                        targetMsg.Options.Add(optionItem.Option);
                    }
                }
            }

            foreach(IDHCPMessageInterceptor interceptor in _interceptors)
            {
                interceptor.Apply(sourceMsg, targetMsg);
            }
        }`

The OLD program did use for **ProcessingReceiveMessage** to send a DHCP-Bootfile.

Did someone has experience with this DHCPServer Code and Linux?

**Comment by jpmikkers** [comment]
Hi, which branch did you base your build on?

**Comment by n-ice-ch** [comment]
Hi,

I've used the master branch.

It is a part of a project to have a PXE Server with DHCP & TFTP. I was inspired by this project: https://github.com/Shkarlatov/PXE-Server

Under Windows, I get the following screen when a client request DHCP:
`TestDHCP - Configuration:
BindAddress: 192.168.2.102
NetMask: 255.255.255.0
Verbose: True
DHCPPort: 67
HTTPPort: 80
TFTPPort: 69
ServerDirectory:
Loader: IPXE
TFTPWindowSize: 8

Starting DHCP server '192.168.2.102:67'
DHCP Server start succeeded

DHCP server is running. Press any key to exit the server.
aPress ENTER to exit
**Incoming packet - parsing DHCP Message**`
...and so on.

Under Linux, I get the following screen when a client request DHCP:
`sudo dotnet TestDHCP.dll
TestDHCP - Configuration:
BindAddress: 192.168.2.155
NetMask: 255.255.255.0
Verbose: True
DHCPPort: 67
HTTPPort: 80
TFTPPort: 69
ServerDirectory:
Loader: IPXE
TFTPWindowSize: 8

Starting DHCP server '192.168.2.155:67'
DHCP Server start succeeded

DHCP server is running. Press any key to exit the server.`
...nothing more happens

Here is a test project to see what I did:
https://github.com/n-ice-ch/TestDHCP

**Comment by jpmikkers** [comment]
In Linux, use netstat to see if your process is listening to port 67. (It probably is though)

if nothing happens after that it's because your firewall is blocking traffic to port 67 on the NIC you bind to.

**Comment by jpmikkers** [comment]
from your first screenshot, it's clearly listening to UDP port 67

**Comment by jpmikkers** [comment]
Better to track this under issue #21

**Comment by n-ice-ch** [comment]
After your hint that the port is listened to and after I tried to send a direct packet instead of a broadcast on UDP 67, I realised that it is better not to bind to an IP address.

There is also an article on this here:
https://stackoverflow.com/questions/74940771/not-receiving-broadcast-udp-messages-when-binding-to-specific-address
