### ISSUE TITLE
Possible null ptr exception

### ISSUE THREAD

**Issue by HEllRZA** [jpmikkers/DHCPServer#6]
https://github.com/jpmikkers/DHCPServer/blob/34333bf0bc39eec7194fa647710bf54f39fd6390/DHCPServer/Library/DHCPServer.cs#L1016

`knownClient` may be `null` here

Fix:
replace `knownClient.LeaseDuration`  with `client.LeaseDuration`

**Comment by jpmikkers** [comment]
Solved with c26235e1199865b51b9b0177bfdd9fb873732cf9
