### ISSUE TITLE
DHCP Option 50 Question

### ISSUE THREAD

**Issue by jmannt3ther** [jpmikkers/DHCPServer#7]
Hi, we are evaluating your library and it works very well. We do have a question however. It seems that our windows devices are sending option 50 and the dhcp server is respecting it. We have removed the reference to option 50 in the dhcp message but that is causing other issues.

Line 208 In DHCPMessage.cs
                //optionsTemplates[(int)TDHCPOption.RequestedIPAddress] = new DHCPOptionRequestedIPAddress();

Basically you can replicate like this:
1. Set dhcp range to something 192.168.x.75-85
2. Connect another windows pc, the first one will get .75
3. Change the range to 192.168.x.100-125
4. When the laptop from item 2 above reconnects it will send an option 50 and try to request .75 and the dhcp server will not offer another ip.

We want to not allow this requestedIPAddress and force the client to get a new IP in the range of .100-125, or just in general ALWAYS force a new ip to the client requesting.

**Comment by jpmikkers** [comment]
Ah got it. When you modify the DHCP range, the server does not clear the existing reservations that are no longer within range. That causes the RENEW logic in the DHCP server to operate on stale/invalid reservations.

A workaround would be to stop the server, delete the file that contains the reservations ( located at  **%ProgramData%\JPMikkers\DHCP Server\name_X_X_X_X.xml** ) , and start the server again.

**Comment by jpmikkers** [comment]
Check out [this branch](/jpmikkers/DHCPServer/tree/filter_illegal_reservations) for a fix.

**Comment by marceloinacio** [comment]
Hi @jpmikkers , @jmannt3ther told me to update our side with the last fix.
I had to add SendNAK(dhcpMessage);
before this line and it's working
https://github.com/jpmikkers/DHCPServer/blob/filter_illegal_reservations/DHCPServer/Library/DHCPServer.cs#L1066

Thank you so much
