### ISSUE TITLE
Can't Start  when changing the folder name

### ISSUE THREAD

**Issue by openroc** [jpmikkers/DHCPServer#9]
it seems that the registered DHCP server service depends running folder path.  and can't uninstall or reinstall service.

**Comment by mawyju** [comment]
Just make sure you have the DHCPServer.exe file in the location where you had it when you installed it, then uninstall, and you'll be good to reinstall it from new location just fine.

**Comment by jpmikkers** [comment]
you can also uninstall manually. 

- make sure the service isn't running via commandline **net stop dhcpserver**
- then call **DHCPServer.exe /unregister**
